sudo : required
sevices:
    - docker

before_install:
    - docker build -t docker-react -f Dockerfile.dev .

scripts:
    - docker run -e CI=true docker-react npm run test -- --coverage

deploy: 
    provider: elasticbeanstalk 
    region: "us-east-2"
    app: "docker-react-1"
    env: "DockerReact1-env"
    bucket_name: "elasticbeanstalk-us-east-2-322729342396"
    bucket_path: "docker-react-1"
    on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"
        